output = "db/pgrepo/seeds"
sqlboiler-models = "github.com/LaysDragon/blog/apps/server/db/pgrepo/models"
wipe = true
add-soft-deletes = true

[psql]
dbname = "dbname"
host = "host"
port = 5432
pass = "pass"
user = "user"
sslmode = "disable"
