// Code generated by SQLBoiler boilingseed-0.1.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package seeds

import (
	"context"
	"fmt"
	"math"
	"strconv"
	"time"

	models "github.com/LaysDragon/blog/apps/server/db/pgrepo/models"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
)

var (
	accountColumnsWithDefault = []string{"id", "created_at", "updated_at", "deleted_at"}
	accountDBTypes            = map[string]string{`ID`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `DeletedAt`: `timestamp with time zone`, `Username`: `character varying`, `Role`: `character varying`, `Email`: `character varying`, `PasswdHash`: `character varying`}
)

// defaultRandomAccount creates a random model.Account
// Used when RandomAccount is not set in the Seeder
func defaultRandomAccount() (*models.Account, error) {
	o := &models.Account{}
	seed := randomize.NewSeed()
	err := randomize.Struct(seed, o, accountDBTypes, true, accountColumnsWithDefault...)

	return o, err
}

func (s Seeder) seedAccounts(ctx context.Context, exec boil.ContextExecutor) error {
	fmt.Println("Adding Accounts")
	AccountsToAdd := s.MinAccountsToSeed

	randomFunc := s.RandomAccount
	if randomFunc == nil {
		randomFunc = defaultRandomAccount
	}

	for i := 0; i < AccountsToAdd; i++ {
		// create model
		o, err := randomFunc()
		if err != nil {
			return fmt.Errorf("unable to get Random Account: %w", err)
		}

		// insert model
		if err := o.Insert(ctx, exec, boil.Infer()); err != nil {
			return fmt.Errorf("unable to insert Account: %w", err)
		}
	}

	// run afterAdd
	if s.AfterAccountsAdded != nil {
		if err := s.AfterAccountsAdded(ctx); err != nil {
			return fmt.Errorf("error running AfterAccountsAdded: %w", err)
		}
	}

	fmt.Println("Finished adding Accounts")
	return nil
}

// These packages are needed in SOME models
// This is to prevent errors in those that do not need it
var _ = math.E
var _ = queries.Query{}

// This is to force strconv to be used. Without it, it causes an error because strconv is imported by ALL the drivers
var _ = strconv.IntSize

// account is here to prevent erros due to driver "BasedOnType" imports.
type account struct {
	ID         int
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  null.Time
	Username   string
	Role       string
	Email      string
	PasswdHash string
}
