// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccessLog   string
	Account     string
	Attachtment string
	Comment     string
	Post        string
}{
	AccessLog:   "access_log",
	Account:     "account",
	Attachtment: "attachtment",
	Comment:     "comment",
	Post:        "post",
}
